
# Base image from jupyter
ARG BASE_CONTAINER=jupyter/pyspark-notebook:spark-3.2.1
FROM $BASE_CONTAINER

LABEL email="mintspecter@gmail.com"
LABEL name="mintspecter"
LABEL version="0.1"
LABEL description="Pyspark Notebook for Geo-Spatial"

# Install spatial packages
