version: "3.7"
services:
  notebook:
    image: "docker.io/mintspecter/geospatial-notebook:latest"
    ports:
      - "8888:8888"
    volumes:
      - work:/home/jovyan/work2
    environment:
      - JUPYTER_TOKEN=test
volumes:
  work:
