version: "3.7"
services:
  notebook:
    image: "docker.io/mintspecter/geospatial-notebook:latest"
    ports:
      - "8888:8888"
    volumes:
      - work:/home/jovyan/work:rw
      - ./data:/home/jovyan/data:ro
    user: 1000:100
    privileged: true
    environment:
      - JUPYTER_TOKEN=test
      - CHOWN_HOME=true
      - CHOWN_HOME_OPTS=-R
volumes:
  work:
